### PR TITLE
sweep: add report-wns for a sweep of values

### PR DESCRIPTION
**Pull request by oharboe**
@jeffng-or FYI

Stage: cts
| Variant                   | base         | 1            | 2            | 3            | 4            | 10           | 11           | 12           |
|---------------------------|--------------|--------------|--------------|--------------|--------------|--------------|--------------|--------------|
| crpr                      | 2.13         | 2.1          | 1.94         | 1.37         | 1.37         | 2.13         | 2.13         | 2.13         |
| skew                      | 122.0        | 153.47       | 121.37       | 135.87       | 147.38       | 122.0        | 122.0        | 122.0        |
| slack                     | -1966.328857 | -1766.296021 | -1752.456665 | -1838.149658 | -2002.130737 | -1966.328857 | -1877.977295 | -1966.328857 |
| tns                       | -128422560.0 | -114425968.0 | -104184936.0 | -123248480.0 | -110017832.0 | -128422560.0 | -124259056.0 | -128422560.0 |
| GPL_TIMING_DRIVEN         |              |              |              |              |              | 0            | 0            | 0            |
| PLACE_DENSITY             |              | 0.25         | 0.21         | 0.22         | 0.23         |              |              |              |
| REMOVE_ABC_BUFFERS        |              |              |              |              |              | 1            | 1            | 1            |
| SKIP_CTS_REPAIR_TIMING    |              |              |              |              |              |              | 0            | 1            |
| SKIP_INCREMENTAL_REPAIR   |              |              |              |              |              |              |              | 0            |
| 2_1_floorplan.log         | 230          | 273          | 251          | 251          | 250          | 251          | 251          | 251          |
| 2_2_floorplan_io.log      | 27           | 31           | 30           | 29           | 29           | 29           | 29           | 29           |
| 2_3_floorplan_tdms.log    | 0            | 0            | 0            | 0            | 0            | 0            | 0            | 0            |
| 2_4_floorplan_macro.log   | 757          | 1071         | 1316         | 1334         | 1345         | 1127         | 1134         | 1132         |
| 2_5_floorplan_tapcell.log | 25           | 28           | 28           | 28           | 27           | 27           | 27           | 27           |
| 2_6_floorplan_pdn.log     | 612          | 679          | 715          | 1244         | 1293         | 771          | 728          | 732          |
| 3_1_place_gp_skip_io.log  | 467          | 1027         | 563          | 570          | 595          | 670          | 677          | 680          |
| 3_2_place_iop.log         | 41           | 46           | 44           | 44           | 43           | 44           | 43           | 45           |
| 3_3_place_gp.log          | 3068         | 4341         | 3594         | 3898         | 2909         | 4210         | 4259         | 4280         |
| 3_4_place_resized.log     | 733          | 731          | 767          | 761          | 797          | 730          | 732          | 732          |
| 3_5_place_dp.log          | 1494         | 1506         | 1733         | 1685         | 1698         | 1847         | 1617         | 1687         |
| 4_1_cts.log               | 550          | 546          | 573          | 568          | 575          | 640          | 6503         | 672          |

Base configuration variables
| Variable                 | Value                                                 |
|--------------------------|-------------------------------------------------------|
| CORE_AREA                | 2 2 1498 1498                                         |
| DIE_AREA                 | 0 0 1500 1500                                         |
| FILL_CELLS               |                                                       |
| GPL_ROUTABILITY_DRIVEN   | 1                                                     |
| GPL_TIMING_DRIVEN        | 0                                                     |
| IO_CONSTRAINTS           | $(location :io-boomtile)                              |
| MACRO_PLACE_HALO         | 19 19                                                 |
| MAX_ROUTING_LAYER        | M7                                                    |
| MIN_ROUTING_LAYER        | M2                                                    |
| PDN_TCL                  | $(PLATFORM_DIR)/openRoad/pdn/BLOCKS_grid_strategy.tcl |
| PLACE_DENSITY            | 0.20                                                  |
| PLACE_PINS_ARGS          | -annealing                                            |
| REMOVE_ABC_BUFFERS       | 1                                                     |
| ROUTING_LAYER_ADJUSTMENT | 0.45                                                  |
| RTLMP_FLOW               | 1                                                     |
| SDC_FILE                 | $(location :constraints-boomtile)                     |
| SKIP_CTS_REPAIR_TIMING   | 1                                                     |
| SKIP_INCREMENTAL_REPAIR  | 1                                                     |
| SKIP_REPORT_METRICS      | 1                                                     |
| SYNTH_HIERARCHICAL       | 1                                                     |
| TAPCELL_TCL              |                                                       |
| TNS_END_PERCENT          | 0                                                     |

### CODE REVIEW

**Comment by oharboe** [comment]
Still running after 13 hours:

```
   Iter   | Removed | Resized | Inserted | Cloned |  Pin  |    WNS   |   TNS      |  Viol  | Worst
          | Buffers |  Gates  | Buffers  |  Gates | Swaps |          |            | Endpts | Endpt
---------------------------------------------------------------------------------------------------
        0 |       0 |       0 |        0 |      0 |     0 | -2195.436 | -114376600.0 | 165887 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
       10 |       0 |       7 |        0 |      1 |     1 | -1346.351 | -80619768.0 | 165887 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
[deleted]
     563* |       0 |     193 |        9 |     24 |    29 | -1050.290 | -55556012.0 |  95339 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
     564* |       0 |     193 |        9 |     24 |    29 | -1050.290 | -55556004.0 |  95339 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
     565* |       0 |     193 |        9 |     24 |    29 | -1050.290 | -55555996.0 |  95339 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
     566* |       0 |     193 |        9 |     24 |    29 | -1050.290 | -55555988.0 |  95339 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
     567* |       0 |     193 |        9 |     24 |    29 | -1050.290 | -55555984.0 |  95339 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
     568* |       0 |     193 |        9 |     24 |    29 | -1050.290 | -55555976.0 |  95339 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
     569* |       0 |     193 |        9 |     24 |    29 | -1050.290 | -55555968.0 |  95339 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
     570* |       0 |     193 |        9 |     24 |    29 | -1050.290 | -55555968.0 |  95339 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
     570* |       0 |     193 |        9 |     24 |    29 | -1050.290 | -55555960.0 |  95339 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
     571* |       0 |     193 |        9 |     24 |    29 | -1050.290 | -55555952.0 |  95339 | core/int_issue_unit/io_dis_uops_0_ready_REG$_DFF_P_/D
```

**Comment by maliberty** [comment]
Is this with the change I suggested today?

**Comment by oharboe** [comment]
> Is this with the change I suggested today?

Not yet :-)  It's not ice yet... https://www.youtube.com/watch?v=VMoqttrEmxM

What makes things "run forever" is `REMOVE_ABC_BUFFERS=1`

**Comment by oharboe** [comment]
image

**Comment by oharboe** [comment]
Stage: floorplan
| Variant                   | base          | 1             | 2             | 3             | 4             | 5            | 6            | 7            | 8            |
|---------------------------|---------------|---------------|---------------|---------------|---------------|--------------|--------------|--------------|--------------|
| crpr                      | 0.0           | 0.0           | 0.0           | 0.0           | 0.0           | 0.0          | 0.0          | 0.0          | 0.0          |
| skew                      | 0.0           | 0.0           | 0.0           | 0.0           | 0.0           | 0.0          | 0.0          | 0.0          | 0.0          |
| slack                     | -20958.109375 | -20958.109375 | -20958.109375 | -20958.109375 | -20958.109375 | -1050.289795 | -1050.289795 | -1050.289795 | -1050.289795 |
| tns                       | -1862706304.0 | -1862706304.0 | -1862706304.0 | -1862706304.0 | -1862706304.0 | -55499588.0  | -55499588.0  | -55499588.0  | -55499588.0  |
| GPL_TIMING_DRIVEN         |               |               |               |               |               |              | 1            | 1            | 1            |
| PLACE_DENSITY             |               | 0.25          | 0.21          | 0.22          | 0.23          |              |              |              |              |
| REMOVE_ABC_BUFFERS        |               |               |               |               |               | 0            | 0            | 0            | 0            |
| SKIP_CTS_REPAIR_TIMING    |               |               |               |               |               |              |              | 0            | 0            |
| SKIP_INCREMENTAL_REPAIR   |               |               |               |               |               |              |              |              | 0            |
| 2_1_floorplan.log         | 230           | 273           | 251           | 251           | 250           | 120132       | 120173       | 120661       | 120526       |
| 2_2_floorplan_io.log      | 27            | 31            | 30            | 29            | 29            | 29           | 29           | 30           | 29           |
| 2_3_floorplan_tdms.log    | 0             | 0             | 0             | 0             | 0             | 0            | 0            | 0            | 0            |
| 2_4_floorplan_macro.log   | 757           | 1071          | 1316          | 1334          | 1345          | 1753         | 1774         | 1875         | 1904         |
| 2_5_floorplan_tapcell.log | 25            | 28            | 28            | 28            | 27            | 36           | 33           | 27           | 29           |
| 2_6_floorplan_pdn.log     | 612           | 679           | 715           | 1244          | 1293          | 684          | 673          | 633          | 641          |

Base configuration variables
| Variable                 | Value                                                 |
|--------------------------|-------------------------------------------------------|
| CORE_AREA                | 2 2 1498 1498                                         |
| DIE_AREA                 | 0 0 1500 1500                                         |
| FILL_CELLS               |                                                       |
| GPL_ROUTABILITY_DRIVEN   | 1                                                     |
| GPL_TIMING_DRIVEN        | 0                                                     |
| IO_CONSTRAINTS           | $(location :io-boomtile)                              |
| MACRO_PLACE_HALO         | 19 19                                                 |
| MAX_ROUTING_LAYER        | M7                                                    |
| MIN_ROUTING_LAYER        | M2                                                    |
| PDN_TCL                  | $(PLATFORM_DIR)/openRoad/pdn/BLOCKS_grid_strategy.tcl |
| PLACE_DENSITY            | 0.20                                                  |
| PLACE_PINS_ARGS          | -annealing                                            |
| REMOVE_ABC_BUFFERS       | 1                                                     |
| ROUTING_LAYER_ADJUSTMENT | 0.45                                                  |
| RTLMP_FLOW               | 1                                                     |
| SDC_FILE                 | $(location :constraints-boomtile)                     |
| SKIP_CTS_REPAIR_TIMING   | 1                                                     |
| SKIP_INCREMENTAL_REPAIR  | 1                                                     |
| SKIP_REPORT_METRICS      | 1                                                     |
| SYNTH_HIERARCHICAL       | 1                                                     |
| TAPCELL_TCL              |                                                       |
| TNS_END_PERCENT          | 0                                                     |

**Comment by oharboe** [comment]
@maliberty @jeffng-or 120000 seconds for REMOVE_ABC_BUFFERS=0 and negative slack of -1050, see table above.

Clearly, and as expected and exactly as Matt told us, we have to run retiming.

**Comment by oharboe** [comment]
merged with main

**Pull request closed without merging**
