### PR TITLE
variants: measure all the way through grt

### PR DESCRIPTION
**Pull request by oharboe**
@jeffng-or @maliberty Let's see what is going on with WNS in floorplan, place, cts and grt...

### CODE REVIEW

**Comment by oharboe** [comment]
@jeffng-or @vvbandeira Has the server crashed?

**Comment by oharboe** [comment]
@vvbandeira @jeffng-or Server seems to be crashed. This PR is irrelevant, we can't look at timing for grt before we have global routing that completes.

**Comment by vvbandeira** [comment]
> @jeffng-or @vvbandeira Has the server crashed?

> @vvbandeira @jeffng-or Server seems to be crashed. This PR is irrelevant, we can't look at timing for grt before we have global routing that completes.

Why do you think the server has crashed? I don't see any indication of that; the build was running when you closed the PR.

**Comment by oharboe** [comment]
> > @jeffng-or @vvbandeira Has the server crashed?
> 
> > @vvbandeira @jeffng-or Server seems to be crashed. This PR is irrelevant, we can't look at timing for grt before we have global routing that completes.
> 
> Why do you think the server has crashed? I don't see any indication of that; the build was running when you closed the PR.

There was no way to navigate from the PR to the running build, so I could see no evidence that the build was running. I will take a screenshot next time.

**Pull request closed without merging**
