### PR TITLE
docker vestiges: delete

### PR DESCRIPTION
**Pull request by oharboe**
.bazelrc modifications are no longer needed

### CODE REVIEW

**Comment by oharboe** [comment]
@eszpotanski OK?

**Comment by oharboe** [comment]
@eszpotanski Better now?

**Comment by oharboe** [comment]
@hovind FYI

**Comment by oharboe** [comment]
@maliberty @jeffng-or FYI

**Review by eszpotanski — APPROVED** [review]
LGTM

**Pull request merged**
