### PR TITLE
bazel-orfs: bump

### PR DESCRIPTION
**Pull request by oharboe**
@jeffng-or I'm confused... Trying a bump to see if the problem is fixed.

```
bazel run BoomTile_cts `pwd`/tmp
tmp/make gui_cts
```

Fails on main:

```
external/bazel-orfs~~orfs_repositories~docker_orfs/OpenROAD-flow-scripts/flow/Makefile:177: platforms/asap7/config.mk: No such file or directory
make: *** No rule to make target 'platforms/asap7/config.mk'.  Stop.
```

Also:

```
$ bazel run BoomTile_cts `pwd`/tmp  gui_cts
[deleted]
  bazel-bin/results/asap7/BoomTile/base/4_cts.odb
  bazel-bin/results/asap7/BoomTile/base/4_cts.sdc
INFO: Elapsed time: 0.107s, Critical Path: 0.04s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/BoomTile_cts.sh /home/oyvind/megaboom/tmp gui_cts
external/bazel-orfs~~orfs_repositories~docker_orfs/OpenROAD-flow-scripts/flow/Makefile:177: platforms/asap7/config.mk: No such file or directory
make: *** No rule to make target 'platforms/asap7/config.mk'.  Stop.
```

### CODE REVIEW

**Comment by oharboe** [comment]
@jeffng-or @vvbandeira @maliberty Artifacts are being uploaded by Jenkins, near as I can tell. :100: 

Tested locally with `bazel build BoomTile_synth_deps`. There's one being downloaded, the rest haven't been built on the server as of writing. 

image

**Comment by oharboe** [comment]
passed floorplan, merging. Presumably jenkins will keep running and build artifacts, but now main is no longer broken after bazel-orfs bump

**Comment by oharboe** [comment]
Ouch. still broken.

```
$ tmp/make gui_floorplan
ODB_FILE=.//results/asap7/BoomTile/base/2_floorplan.odb /home/oyvind/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad -no_init -threads 16  /home/oyvind/OpenROAD-flow-scripts/flow/scripts/open.tcl
OpenROAD v2.0-16443-g372a00c48 
Features included (+) or not (-): +Charts +GPU +GUI +Python
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
[INFO ORD-0030] Using 16 thread(s).
Error: read_liberty.tcl, 25 cannot read file results/asap7/array_256x128/base/array_256x128.lib.
openroad> 
```

**Comment by oharboe** [comment]
Workaround:

rm -rf tmp && bazel run L1MetadataArray_floorplan_deps `pwd`/tmp && bazel run L1MetadataArray_floorplan `pwd`/tmp gui_floorplan

Fails:

rm -rf tmp && bazel run L1MetadataArray_floorplan `pwd`/tmp gui_floorplan

**Comment by jeffng-or** [comment]
I ran into the same issues using main.

FWIW, I happened to be running with megaboom tag v2 and it looks like both sets of data (e.g. the platforms directory and the SRAM results) are exported. So, did something change in bazel-orfs?

**Comment by oharboe** [comment]
Mea culpa...

We've got a workaround above...

Will fix Monday...

image

**Pull request merged**
