### PR TITLE
updated SDCs to define both read and write clocks

### PR DESCRIPTION
**Pull request by jeffng-or**
PR to update SRAM SDC file to define both clocks

### CODE REVIEW

**Review by oharboe — CHANGES_REQUESTED** [review]
create a new constraints-sram.sdc and leave constraints.sdc unchanged and use constraints-sram.sdc from SRAMs by updating BUILD.bazel

**Comment by jeffng-or** [comment]
> Isnt this also used by BoomTile? In which case we need an additional .sdc file.
> 
> Also, the BUILD bazel need to be updated to use the file.

If I read the BUILD.bazel correctly, the current constraints.sdc is used by the SRAM, regfile, and L1MetadataArray abstract generation flows. It is not used by BoomTile (it uses constraints-boomtile.sdc).

But, yes, the proposed change wouldn't work for dataArrayB, tag_array*, or L1MetadataArray, since their clocks are named either RW0_clk, R*_clk, W*_clk or just clock.

So, it seems like we might be able to:

1. Modify the existing constraints.sdc to use *_clk to find the clock ports and use it for all SRAMs and regfiles
2. Have L1MetadataArray continue to use the existing constraints-boomtile.sdc since they both have just "clock"

Please correct me if I'm wrong, but I think that will hook up the appropriate clocks for the abstract generation flow.

**Comment by oharboe** [comment]
Yes, this should work.

**Review by oharboe — APPROVED** [review]
lgtm.

should this have gone  through jenkins CI?

**Comment by jeffng-or** [comment]
> lgtm.
> 
> should this have gone through jenkins CI?

Interesting, the Jenkins CI jobs got kicked off and passed:

https://jenkins.openroad.tools/job/megaboom-Public/view/change-requests/job/PR-118-head/
https://jenkins.openroad.tools/job/megaboom-Public/view/change-requests/job/PR-118-merge/

Maybe there needs to be some hook up in GitHub so that it shows up in the Rules section? @vvbandeira , how do we register the CI as a check?

**Pull request merged**
