### PR TITLE
1500x1500

### PR DESCRIPTION
**Pull request by oharboe**
image

### CODE REVIEW

**Comment by oharboe** [comment]
@jeffng-or @maliberty FYI, smaller layout now with the SRAMs having the sizes that Jeff calculated.

**Comment by maliberty** [comment]
@oharboe what did you base halving the size on?

**Comment by maliberty** [comment]
So you didn't halve the size Jeff calculated so much as you fixed a bug that caused them to be bigger than Jeff's size?

**Comment by oharboe** [comment]
> So you didn't halve the size Jeff calculated so much as you fixed a bug that caused them to be bigger than Jeff's size?

Exactly.

Though a few of them for d/i cache are now bigger, but even so, much smaller die area.

**Pull request merged**
