### PR TITLE
README: Update the usage instructions

### PR DESCRIPTION
**Pull request by lpawelcz**
@oharboe

This PR depends on https://github.com/The-OpenROAD-Project/bazel-orfs/pull/27. Some of the instructions added here refer to GUI targets that are yet to be introduced to bazel-orfs. After merging https://github.com/The-OpenROAD-Project/bazel-orfs/pull/27 we should pin new `bazel-orfs` version in [MODULE.bazel](https://github.com/The-OpenROAD-Project/megaboom/blob/main/MODULE.bazel#L11) and then merge this PR.

We also decided to remove `Creating an issue report` paragraph because we feel that it belongs to `bazel-orfs` documentation and will be added there alongside the support for `make issue` targets.
Perhaps most of the `Tutorial` chapter should eventually end up in `bazel-orfs`.
Please let us know what do you think.

### CODE REVIEW

**Comment by oharboe** [comment]
@lpawelcz all generic documentation on bazel-orfs should go into bazel-orfs. megaboom docs should contain little repetition of what is in bazel-orfs and mainly megaboom specific documentation.

**Comment by lpawelcz** [comment]
@oharboe moved `Tutorial` paragraph to `bazel-orfs` README in https://github.com/The-OpenROAD-Project/bazel-orfs/pull/29.
We've left a small part of this tutorial in megaboom README to warn the users to use correct label when downloading the docker image with `orfs_env` target.

**Comment by lpawelcz** [comment]
CI failure is unrelated. To be fixed in https://github.com/The-OpenROAD-Project/megaboom/pull/45.

**Comment by oharboe** [comment]
Let us just start with cleanup as a new baseline for documentation, even if there's more work to be done in bazel-orfs.

**Pull request merged**
