### PR TITLE
Wns report description

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by oharboe** [comment]
@maliberty @jeffng-or @xtofalex Flattend synthesis reduces number of instances by 50%

variant 2, flattened synthesis:

image

variant base, hierarchical synthesis:

image

**Comment by maliberty** [comment]
This is why we have the two pass synthesis in ORFS to selectively flatten.  Most likely you can keep the upper levels of hierarchy without much QOR difference.

**Comment by oharboe** [comment]
> This is why we have the two pass synthesis in ORFS to selectively flatten. Most likely you can keep the upper levels of hierarchy without much QOR difference.

I could run lots of synthesis runs to try to figure out what effect flattening which modules has on the QoR, though I'm unsure what I would do with this information. At this point, I'd just flatten everything anyway.

hierarchical synthesis is valuable to help the macro placer, but once I have the macro placement, flattening everything is the best policy I'm aware of.

**Comment by maliberty** [comment]
That's a viable strategy for a completely frozen design.  Not as good if you are making rtl changes where new logic could influence macro placement.

**Comment by oharboe** [comment]
> That's a viable strategy for a completely frozen design. Not as good if you are making rtl changes where new logic could influence macro placement.

Changing RTL is not a problem for the megaboom flow:

1. run hierarchical, generate macro placement file
2. run flattened, use macro placement file

so I get flattened synthesis and automatic macro placement based upon hierachical synthesis.

Running time increases by 50% for synthesis since it is 3x instead of 2x.

**Comment by oharboe** [comment]
> This line of thinking assumes that standard cells don't affect macro placement but that isn't true. If you have 50% less std cell area then you could, for example, move the macros closer together. mpl2 does consider both macros and std cells.

Well.... I was told to use SYNTH_HIERARCHICAL=1 with automatic macro placement, but that doubles the number of instances, so perhaps in this case, SYNTH_HIERARCHICAL=0 & macro place yields better results?

A think to try....

**Comment by oharboe** [comment]
Some more reporting. Not pretty, but good 'nuf for use around the house.

Stage: cts
| Variant                        | base         | 2                                         |
|--------------------------------|--------------|-------------------------------------------|
| Description                    |              | Same as base, but with flattend synthesis |
| Buffer                         | 264492       | 119157                                    |
| Clock buffer                   | 23052        | 12067                                     |
| Clock inverter                 | 6997         | 3634                                      |
| Inverter                       | 141051       | 62571                                     |
| Macro                          | 72           | 72                                        |
| Multi-Input combinational cell | 1365515      | 745216                                    |
| Sequential cell                | 239698       | 118443                                    |
| Tie cell                       | 2578         | 60                                        |
| Timing Repair Buffer           | 88407        | 43364                                     |
| Total                          | 2131862      | 1104584                                   |
| slack                          | -5494.812988 | -3262.439697                              |
| MACRO_PLACEMENT_TCL            |              | 0                                         |
| SYNTH_HIERARCHICAL             | 1146         | $(location write_macro_placement)         |
| dissolve                       | 37           |                                           |
| 2_1_floorplan.log              | 1519         | 566                                       |
| 2_2_floorplan_io.log           | 35           | 20                                        |
| 2_3_floorplan_macro.log        | 895          | 22                                        |
| 2_4_floorplan_tapcell.log      | 1596         | 18                                        |
| 2_5_floorplan_pdn.log          | 49           | 874                                       |
| 3_1_place_gp_skip_io.log       | 6140         | 1954                                      |
| 3_2_place_iop.log              | 610          | 28                                        |
| 3_3_place_gp.log               | 1474         | 3907                                      |
| 3_4_place_resized.log          | 543          | 328                                       |

Base configuration variables
| Variable                 | Value                                                 |
|--------------------------|-------------------------------------------------------|
| CORE_AREA                | 2 2 1998 1998                                         |
| DIE_AREA                 | 0 0 2000 2000                                         |
| FILL_CELLS               |                                                       |
| GPL_ROUTABILITY_DRIVEN   | 1                                                     |
| GPL_TIMING_DRIVEN        | 0                                                     |
| HOLD_SLACK_MARGIN        | -200                                                  |
| IO_CONSTRAINTS           | $(location :io-boomtile)                              |
| MACRO_PLACE_HALO         | 19 19                                                 |
| MAX_ROUTING_LAYER        | M7                                                    |
| MIN_ROUTING_LAYER        | M2                                                    |
| PDN_TCL                  | $(PLATFORM_DIR)/openRoad/pdn/BLOCKS_grid_strategy.tcl |
| PLACE_DENSITY            | 0.24                                                  |
| PLACE_PINS_ARGS          | -annealing                                            |
| ROUTING_LAYER_ADJUSTMENT | 0.45                                                  |
| SDC_FILE                 | $(location :constraints-boomtile)                     |
| SETUP_SLACK_MARGIN       | -1300                                                 |
| SKIP_CTS_REPAIR_TIMING   | 1                                                     |
| SKIP_INCREMENTAL_REPAIR  | 1                                                     |
| SKIP_LAST_GASP           | 1                                                     |
| SKIP_REPORT_METRICS      | 1                                                     |
| SYNTH_HIERARCHICAL       | 1                                                     |
| TAPCELL_TCL              |                                                       |
| TNS_END_PERCENT          | 0                                                     |

**Comment by maliberty** [comment]
SYNTH_HIERARCHICAL is not the only control.  With some care you use MAX_UNGROUP_SIZE to get minimal QOR loss and keep much of the hierarchy.

**Comment by oharboe** [comment]
> SYNTH_HIERARCHICAL is not the only control. With some care you use MAX_UNGROUP_SIZE to get minimal QOR loss and keep much of the hierarchy.

I see. I figure that turning the knob all the way to one side, I can see if it does anything at all... Tinkering with the knob comes later.

**Pull request merged**
