### PR TITLE
variants: macro placement from hierarchical synthesis

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by oharboe** [comment]
@vvbandeira @jeffng-or the server no longer picks up new jobs from megaboom PRs.

**Comment by maliberty** [comment]
If you click the Details link do you not see Jenkins?

**Comment by oharboe** [comment]
> If you click the Details link do you not see Jenkins?

It works now, but earlier today it was stuck and just showing the start and end circles with a grey line between.

When I got the email from Vitor, it worked.

**Comment by maliberty** [comment]
The job may just have been queued and waiting for a worker.

**Comment by oharboe** [comment]
> The job may just have been queued and waiting for a worker.

Yep. I started some jobs with lots of parallel grt runs, which caused some server crashes and I was wondering if the server had recovered and not. I can't tell if there servers are healthy or not, I just see it waiting for the job to start.

**Pull request merged**
